name: washing_love
description: washing_love for Customers


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rating_bar: ^0.2.0
  font_awesome_flutter: ^9.0.0
  buttons_tabbar: ^1.2.1
  email_validator: ^2.0.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  intl:
  package_info: ^2.0.2
  country_code_picker: ^2.0.2
  flutter_easyloading: ^3.0.0
  ff_navigation_bar: ^0.1.5
  pin_code_fields: ^7.2.0
  dcdg: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
   - family:  AppIcon
     fonts:
       - asset: assets/icon/AppIcon.ttf

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

